   # JavaBeans Coffee Sales Analysis
   ## Part 1: Construct the DataFrame

In [13]:
   import pandas as pd

   coffee_sales = pd.DataFrame(
       {
           "Americano": [5628, 6239],
           "Latte": [12426, 25384],
           "Espresso": [852, 756],
           "Cappuccino": [8522, 7561],
       },
       index=["2021 Sales", "2022 Sales"],
   )
   coffee_sales.index.name = "Year"

   coffee_sales

            Americano  Latte  Espresso  Cappuccino
Year
2021 Sales       5628  12426       852        8522
2022 Sales       6239  25384       756        7561

In [14]:
# Sum down each column (across both years)
total_volume = coffee_sales.sum()
print(total_volume)

sales_with_totals = coffee_sales.copy()
sales_with_totals.loc["Total"] = total_volume
sales_with_totals

Americano     11867
Latte         37810
Espresso       1608
Cappuccino    16083
dtype: int64

            Americano  Latte  Espresso  Cappuccino
Year
2021 Sales       5628  12426       852        8522
2022 Sales       6239  25384       756        7561
Total           11867  37810      1608       16083

In [15]:
# (2022 - 2021) / 2021 * 100
yoy_growth = (
    (coffee_sales.loc["2022 Sales"] - coffee_sales.loc["2021 Sales"])
    / coffee_sales.loc["2021 Sales"]
    * 100
).round(2)

yoy_growth

Americano      10.86
Latte         104.28
Espresso      -11.27
Cappuccino    -11.28
dtype: float64

In [16]:
for year in coffee_sales.index:
    row = coffee_sales.loc[year]
    print(f"{year}: best = {row.idxmax()} ({row.max()}), least = {row.idxmin()} ({row.min()})")

2021 Sales: best = Latte (12426), least = Espresso (852)
2022 Sales: best = Latte (25384), least = Espresso (756)

Best and least sellers: Latte was the top seller in both 2021 (12,426) and 2022 (25,384). 
Espresso was the lowest in both years (852 and 756).

Strategic analysis: Latte is JavaBeans' clear growth engine, with sales more than doubling (+104%) and the largest total volume across the two years. Americano is a smaller but healthy performer (+10.9%), so modest, steady support makes sense. Espresso and Cappuccino both declined by about 11%. Cappuccino still has solid volume (7,561 in 2022), so it may benefit from a refresh, like a new recipe, a bundle with a pastry, or a limited-time variation, rather than being cut. Espresso has the lowest volume and a declining trend, so it's the best candidate to redesign (for example, as a base for other drinks or a promotional shot add-on) or to phase out if it doesn't serve a strategic role like attracting coffee purists.

Caveat: This is only two data points and says nothing about price or profit margin. Before dropping any product, leadership should check profitability and whether low-volume items drive other purchases.